server:
  port : 8080
  
spring:
  application:
    name: "xogameserver"
  datasources:
    default:
      url: "jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE"
      username: "sa"
      password: ""
      driver-class-name: "org.h2.Driver"
  liquibase:
    enabled: true
    drop-first: false
    change-log: "classpath:db/changelog-master.yml"
